// Generates the frontend map from the team page's local photo paths to Drive IDs.

require("dotenv").config({
  path: require("path").resolve(__dirname, "../../.env"),
});

const fs = require("fs");
const path = require("path");
const axios = require("axios");
const GoogleDriveStorageService = require("../services/storage/GoogleDriveStorageService");
const storageConfig = require("../config/storageConfig");

const DRIVE_API = "https://www.googleapis.com/drive/v3";
const DRIVE_FOLDER_MIME = "application/vnd.google-apps.folder";
const TEAM_IMAGE_PREFIX = "/images/meetteam/";
const TEAM_PROXY_PREFIX = "/api/assets/drive/";
const TEAM_PAGE_PATH = path.resolve(__dirname, "../../../frontend/src/Pages/MeetTeam.js");
const MANIFEST_PATH = path.resolve(
  __dirname,
  "../../../frontend/src/data/teamAssetManifest.js",
);

const authHeaders = (token) => ({ Authorization: `Bearer ${token}` });

const listChildren = async (token, parentId) => {
  const files = [];
  let pageToken;

  do {
    const response = await axios.get(`${DRIVE_API}/files`, {
      params: {
        q: `'${parentId}' in parents and trashed = false`,
        fields: "nextPageToken,files(id,name,mimeType)",
        pageSize: 1000,
        pageToken,
      },
      headers: authHeaders(token),
    });

    files.push(...(response.data.files || []));
    pageToken = response.data.nextPageToken;
  } while (pageToken);

  return files;
};

const findDriveTree = async (token, folderId, prefix = "", result = new Map()) => {
  const children = await listChildren(token, folderId);

  for (const child of children) {
    const relativePath = prefix ? `${prefix}/${child.name}` : child.name;
    if (child.mimeType === DRIVE_FOLDER_MIME) {
      await findDriveTree(token, child.id, relativePath, result);
    } else {
      result.set(relativePath, child);
    }
  }

  return result;
};

const main = async () => {
  const teamFolderId = storageConfig.googleDrive.teamFolderId;
  if (!teamFolderId) {
    throw new Error("GOOGLE_DRIVE_TEAM_FOLDER_ID is not configured");
  }

  const source = fs.readFileSync(TEAM_PAGE_PATH, "utf8");
  const references = [
    ...new Set(source.match(/\/images\/meetteam\/[^"'`\r\n]+/g) || []),
  ];
  const storage = new GoogleDriveStorageService();
  const token = await storage.getAccessToken();
  if (!token) throw new Error("Google Drive credentials did not produce an access token");

  const driveFiles = await findDriveTree(token, teamFolderId);
  const manifest = {};
  const missing = [];

  for (const reference of references) {
    const relativePath = decodeURIComponent(reference.slice(TEAM_IMAGE_PREFIX.length)).replace(
      /\\/g,
      "/",
    );
    const file = driveFiles.get(relativePath);
    if (!file) {
      missing.push(relativePath);
      continue;
    }

    manifest[reference] = `${TEAM_PROXY_PREFIX}${encodeURIComponent(file.id)}?cache=team`;
  }

  if (missing.length > 0) {
    throw new Error(`Drive files missing for: ${missing.join(", ")}`);
  }

  fs.mkdirSync(path.dirname(MANIFEST_PATH), { recursive: true });
  const output = `// Generated by backend/src/utils/syncTeamImagesWithGoogleDrive.js.\nconst teamAssetManifest = ${JSON.stringify(
    manifest,
    null,
    2,
  )};\n\nexport default teamAssetManifest;\n`;
  fs.writeFileSync(MANIFEST_PATH, output);
  console.log(
    `Team image manifest generated: ${references.length} reference(s), ${driveFiles.size} Drive file(s).`,
  );
};

main().catch((error) => {
  console.error(
    `Team image Drive sync failed: ${error.response?.data?.error?.message || error.message}`,
  );
  process.exitCode = 1;
});
